# Generated by Django 4.2.7 on 2024-03-13 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0005_alter_massagechair_brand'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChairComment',
            new_name='ChairReview',
        ),
    ]
