# Generated by Django 4.2.7 on 2024-03-13 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0007_chairreview_poster_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chairreview',
            old_name='comment_text',
            new_name='review_text',
        ),
    ]
