# Generated by Django 4.2.7 on 2024-03-13 09:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0008_rename_comment_text_chairreview_review_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.CharField(default='Massage Chairs', max_length=35)),
                ('response_text', models.TextField(default='')),
                ('responded_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('responded_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soothestore.chairreview')),
            ],
        ),
    ]
