# Generated by Django 4.2.7 on 2024-03-13 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0009_reviewresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='chairreview',
            name='customer_rate',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
