# Generated by Django 4.2.7 on 2024-03-13 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0011_chairfeature_feature_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identity', models.CharField(max_length=50)),
                ('action', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], default='like', max_length=8)),
                ('to_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soothestore.chairreview')),
            ],
        ),
    ]
