# Generated by Django 4.2.7 on 2024-03-13 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0012_useraction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAction',
            new_name='UserReaction',
        ),
    ]
