# Generated by Django 4.2.7 on 2024-03-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0013_rename_useraction_userreaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='massagechair',
            name='brand_name',
            field=models.CharField(blank=True, default='No Brand', max_length=20),
        ),
    ]
