# Generated by Django 4.2.7 on 2024-03-17 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0014_massagechair_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='massagechair',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
