# Generated by Django 5.0.4 on 2024-04-27 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0016_alter_chairfeature_called_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='massagechair',
            name='brand_name',
        ),
        migrations.AlterField(
            model_name='color_options',
            name='color_code',
            field=models.CharField(max_length=50),
        ),
    ]
