# Generated by Django 5.0.4 on 2024-04-28 00:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0018_alter_color_options_color_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Chair Colors',
            },
        ),
        migrations.AlterField(
            model_name='massagechair',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=2, validators=[django.core.validators.MaxValueValidator(limit_value=5.0)]),
        ),
        migrations.AddField(
            model_name='massagechair',
            name='additional_images',
            field=models.ManyToManyField(related_name='additional_product_images', to='soothestore.additionalimages'),
        ),
    ]
