# Generated by Django 5.0.4 on 2024-04-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0019_additionalimages_alter_massagechair_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massagechair',
            name='additional_images',
            field=models.ManyToManyField(related_name='massage_chaira', to='soothestore.color_options'),
        ),
    ]
