# Generated by Django 5.0.4 on 2024-04-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0020_alter_massagechair_additional_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massagechair',
            name='additional_images',
            field=models.ManyToManyField(related_name='additional_product_images', to='soothestore.additionalimages'),
        ),
    ]
