# Generated by Django 5.0.4 on 2024-04-28 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0021_alter_massagechair_additional_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdditionalImages',
            new_name='Additional_Images',
        ),
    ]
