# Generated by Django 5.0.4 on 2024-04-28 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0022_rename_additionalimages_additional_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chairfeature',
            name='called',
            field=models.CharField(default=None, max_length=120),
        ),
        migrations.AlterField(
            model_name='chairfeature',
            name='feature_description',
            field=models.TextField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
