# Generated by Django 5.0.4 on 2024-04-28 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0023_alter_chairfeature_called_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chairfeature',
            name='feature_description',
            field=models.TextField(blank=True, default=None, max_length=655, null=True),
        ),
    ]
