# Generated by Django 5.0.4 on 2024-04-29 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0024_alter_chairfeature_feature_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='chairfeature',
            name='feature_side',
            field=models.ImageField(choices=[('any side', 'any side'), ('left', 'left'), ('right', 'right')], default=('any side', 'any side'), max_length=35, upload_to=''),
        ),
    ]
