# Generated by Django 5.0.4 on 2024-04-29 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0025_chairfeature_feature_side'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoShowcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showcase_text', models.CharField(blank=True, default=None, max_length=460, null=True)),
                ('video_platform', models.CharField(choices=[('youtube', 'youtube'), ('vimeo', 'vimeo')], default='vimeo', max_length=35)),
                ('video_id', models.CharField(default=None, max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Video Demonstrations',
            },
        ),
        migrations.AlterField(
            model_name='chairfeature',
            name='feature_side',
            field=models.CharField(choices=[('any side', 'any side'), ('left', 'left'), ('right', 'right')], default='any side', max_length=35),
        ),
        migrations.AddField(
            model_name='massagechair',
            name='video_demo',
            field=models.ManyToManyField(related_name='video_demonstration', to='soothestore.videoshowcase'),
        ),
    ]
