# Generated by Django 5.0.4 on 2024-04-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0026_videoshowcase_alter_chairfeature_feature_side_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoshowcase',
            name='showcase_text',
            field=models.TextField(blank=True, default=None, max_length=460, null=True),
        ),
    ]
