# Generated by Django 5.0.4 on 2024-04-29 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0027_alter_videoshowcase_showcase_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoshowcase',
            name='showcase_text',
            field=models.TextField(blank=True, default=None, max_length=1200, null=True),
        ),
    ]
