# Generated by Django 5.0.4 on 2024-05-01 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0029_videoshowcase_video_side_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massagechair',
            name='additional_images',
            field=models.ManyToManyField(blank=True, related_name='additional_product_images', to='soothestore.additional_images'),
        ),
        migrations.AlterField(
            model_name='massagechair',
            name='video_demo',
            field=models.ManyToManyField(blank=True, related_name='video_demonstration', to='soothestore.videoshowcase'),
        ),
    ]
