# Generated by Django 5.0.4 on 2024-05-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0031_brand_brand_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='discount_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_title', models.CharField(blank=True, max_length=220, null=True)),
                ('discount_amount', models.IntegerField(default=200)),
                ('discount_type', models.CharField(choices=[('fixed', 'fixed'), ('percentage', 'percentage')], default='fixed', max_length=10)),
                ('is_public', models.BooleanField(default=True)),
                ('discount_code', models.CharField(default=200, max_length=8)),
            ],
        ),
    ]
