# Generated by Django 5.0.4 on 2024-05-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0032_discount_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount_code',
            options={'verbose_name_plural': 'Discounts'},
        ),
        migrations.AlterField(
            model_name='discount_code',
            name='discount_code',
            field=models.CharField(blank=True, default=None, max_length=8, null=True),
        ),
    ]
