# Generated by Django 5.0.4 on 2024-05-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0036_rename_used_users_discount_code_users_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount_code',
            name='users_used',
            field=models.ManyToManyField(blank=True, null=True, related_name='customers_used_this_code', to='soothestore.subscribedcustomers'),
        ),
    ]
