# Generated by Django 5.0.4 on 2024-05-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0037_alter_discount_code_users_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount_code',
            name='users_used',
        ),
        migrations.AddField(
            model_name='subscribedcustomers',
            name='customer_discount_codes',
            field=models.ManyToManyField(blank=True, related_name='customer_discount_code', to='soothestore.discount_code'),
        ),
    ]
