# Generated by Django 5.0.4 on 2024-05-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0038_remove_discount_code_users_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount_code',
            name='eligible',
            field=models.CharField(choices=[('new_customer_only', 'new_customer'), ('everyone', 'everyone')], default='everyone', max_length=17),
        ),
    ]
