# Generated by Django 5.0.4 on 2024-05-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0039_discount_code_eligible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount_code',
            name='eligible',
            field=models.CharField(choices=[('new_customer_only', 'new customer only'), ('everyone', 'everyone')], default='everyone', max_length=17),
        ),
        migrations.AlterField(
            model_name='massagechair',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
