# Generated by Django 5.0.4 on 2024-05-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0040_alter_discount_code_eligible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color_options',
            name='color_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
