# Generated by Django 5.0.4 on 2024-06-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0042_payment_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default=None, max_length=255)),
                ('lastname', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('apartment_or_suite', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('address', models.CharField(default=None, max_length=255)),
                ('country', models.CharField(default='United States', max_length=255)),
                ('zipcode', models.CharField(default=None, max_length=20)),
                ('city', models.CharField(default=None, max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
    ]
