# Generated by Django 5.0.4 on 2024-06-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0044_payment_session_shipping_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippinginformation',
            old_name='apartment_or_suite',
            new_name='apartment_suite',
        ),
        migrations.AddField(
            model_name='payment_session',
            name='order_number',
            field=models.CharField(default=None, max_length=8, unique=True),
        ),
    ]
