# Generated by Django 5.0.4 on 2024-06-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0045_rename_apartment_or_suite_shippinginformation_apartment_suite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_session',
            name='order_number',
            field=models.CharField(default=None, max_length=12, unique=True),
        ),
    ]
