# Generated by Django 5.0.4 on 2024-06-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0046_alter_payment_session_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_session',
            name='payment_amount',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
