# Generated by Django 5.0.4 on 2024-06-15 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0047_payment_session_payment_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment_session',
            old_name='payment_amount',
            new_name='expected_amount',
        ),
    ]
