# Generated by Django 5.0.4 on 2024-06-16 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0050_payment_session_tracking_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_session',
            name='tracking_available',
        ),
    ]
