# Generated by Django 5.0.4 on 2024-06-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0051_remove_payment_session_tracking_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='order_tracking_available',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
