# Generated by Django 5.0.4 on 2024-06-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0052_brand_order_tracking_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='order_tracking_available',
            field=models.BooleanField(default=False),
        ),
    ]
