# Generated by Django 5.0.4 on 2024-06-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0054_product_track'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_track',
            options={'verbose_name_plural': 'Orders Tracks'},
        ),
        migrations.AlterField(
            model_name='product_track',
            name='order_number_provided_by_brand',
            field=models.CharField(default='order number actual brand provides', max_length=35),
        ),
        migrations.AlterField(
            model_name='product_track',
            name='tracking_stage',
            field=models.IntegerField(choices=[(1, 'Order Confirmed'), (2, 'Processing'), (3, 'On the way'), (4, 'Delivered')], default=1, max_length=25),
        ),
    ]
