# Generated by Django 5.0.6 on 2024-06-16 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0055_alter_product_track_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_session',
            name='discount_code_used',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='soothestore.discount_code'),
        ),
        migrations.AlterField(
            model_name='product_track',
            name='tracking_stage',
            field=models.IntegerField(choices=[(1, 'Order Confirmed'), (2, 'Processing'), (3, 'On the way'), (4, 'Delivered')], default=1),
        ),
    ]
