# Generated by Django 5.0.6 on 2024-06-16 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0056_payment_session_discount_code_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_session',
            name='discount_code_used',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
