# Generated by Django 5.0.6 on 2024-06-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0057_alter_payment_session_discount_code_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_session',
            name='first_time_view',
            field=models.BooleanField(default=True),
        ),
    ]
