# Generated by Django 5.0.4 on 2024-07-01 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0058_payment_session_first_time_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribedcustomers',
            name='email',
            field=models.EmailField(max_length=60, unique=True),
        ),
    ]
