# Generated by Django 5.0.4 on 2024-07-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0061_payment_session_associated_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='massagechair',
            name='has_reviewers',
            field=models.BooleanField(default=False),
        ),
    ]
