# Generated by Django 5.0.4 on 2024-07-05 10:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0063_companycontactinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(max_length=255)),
                ('customer_name', models.CharField(max_length=60)),
                ('customer_question', models.TextField(default=None)),
                ('asked_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
