# Generated by Django 5.0.4 on 2024-07-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0065_alter_chairreview_review_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_session',
            name='order_closed',
            field=models.BooleanField(default=False),
        ),
    ]
