# Generated by Django 5.0.4 on 2024-07-23 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0004_alter_tokenproxy_options'),
        ('soothestore', '0069_rename_user_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedToken',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authtoken.token')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            bases=('authtoken.token',),
        ),
    ]
