# Generated by Django 5.0.4 on 2024-08-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0070_advancedtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=620)),
                ('priority', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='customerinquiry',
            name='handled',
            field=models.BooleanField(default=False),
        ),
    ]
