# Generated by Django 5.0.4 on 2024-08-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0071_faq_customerinquiry_handled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='priority',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
