# Generated by Django 4.2.14 on 2024-08-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0072_alter_faq_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_description', models.TextField(blank=True, help_text='Description for SEO, max 160 characters.', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated SEO keywords.', max_length=255)),
                ('og_title', models.CharField(blank=True, help_text='Title for Open Graph, defaults to product title if blank.', max_length=255)),
                ('og_description', models.TextField(blank=True, help_text='Description for Open Graph, defaults to meta_description if blank.', max_length=160)),
                ('og_image', models.URLField(blank=True, help_text='URL of the image for Open Graph.')),
                ('og_url', models.URLField(blank=True, help_text='Canonical URL of the product for Open Graph.')),
                ('og_type', models.CharField(default='product', help_text='Type of content, e.g., product, article, etc.', max_length=50)),
            ],
        ),
    ]
