# Generated by Django 4.2.14 on 2024-08-15 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0073_productmeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='massagechair',
            name='product_meta',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='soothestore.productmeta'),
        ),
    ]
