# Generated by Django 4.2.14 on 2024-08-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0074_massagechair_product_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmeta',
            name='og_image',
            field=models.URLField(blank=True, help_text='URL of the image for Open Graph.', null=True),
        ),
    ]
