# Generated by Django 4.2.14 on 2024-08-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0076_alter_massagechair_product_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmeta',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Description for SEO, max 160 characters.', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='productmeta',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated SEO keywords.', max_length=255, null=True),
        ),
    ]
