# Generated by Django 4.2.14 on 2024-08-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0077_alter_productmeta_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmeta',
            name='og_description',
            field=models.TextField(blank=True, help_text='Description for Open Graph, defaults to meta_description if blank.', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='productmeta',
            name='og_title',
            field=models.CharField(blank=True, help_text='Title for Open Graph, defaults to product title if blank.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productmeta',
            name='og_type',
            field=models.CharField(blank=True, default='product', help_text='Type of content, e.g., product, article, etc.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productmeta',
            name='og_url',
            field=models.URLField(blank=True, help_text='Canonical URL of the product for Open Graph.', null=True),
        ),
    ]
