# Generated by Django 5.0.6 on 2024-09-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0078_alter_productmeta_og_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceIncreaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('increasedBy', models.FloatField()),
            ],
        ),
    ]
