# Generated by Django 5.0.6 on 2024-09-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0079_priceincreasehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='massagechair',
            name='priority_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
