# Generated by Django 5.0.6 on 2024-09-12 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0080_massagechair_priority_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='massagechair',
            old_name='priority_price',
            new_name='initial_price',
        ),
    ]
