# Generated by Django 5.0.6 on 2024-09-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0081_rename_priority_price_massagechair_initial_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('called', models.CharField(default=None, max_length=120)),
                ('left_image', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('right_image', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('mobile_image', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('offer_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('offer_code', models.CharField(default=None, max_length=120)),
                ('offer_active', models.BooleanField(default=True)),
            ],
        ),
    ]
