# Generated by Django 5.0.6 on 2024-09-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0082_specialevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialevent',
            name='show_on_scroll',
            field=models.BooleanField(default=False),
        ),
    ]
