# Generated by Django 5.0.6 on 2024-09-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soothestore', '0084_alter_specialevent_offer_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialevent',
            name='identifier',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
